### ISSUE TITLE
options does not work with multiple options

### ISSUE THREAD

**Issue by jonathanpoelen** [BSFishy/meson-build#3]
With `options: arg1 arg2`, exec uses the equivalent of `ninja .... 'arg1 arg2'`, which isn't 2 options, but only one.

I don't know who's showing the next line, but it's misleading

```
/opt/hostedtoolcache/Python/3.8.2/x64/bin/ninja -C build arg1 arg2
```

**Comment by BSFishy** [comment]
@jonathanpoelen Would you mind providing the project that is having the issue? I want to be able to see the issue in action so I know what can be changed.

**Comment by jonathanpoelen** [comment]
The project is private, so here is a minimal example that reproduces the issue:
[github actions](https://github.com/jonathanpoelen/meson-build-error/runs/569088763?check_suite_focus=true)
[main.yml](https://github.com/jonathanpoelen/meson-build-error/blob/master/.github/workflows/main.yml#L20)

I think that `options` should be an array or splitted on spaces.

**Comment by noah1510** [comment]
setup-options has the same problem. 
At the moment it is only possible to set one option not more than that.

Making that field an array or splitted on spaces would also fix that problem.

**Comment by noah1510** [comment]
#8 should close this issue

**Comment by BSFishy** [comment]
This is fixed in the latest release. Change the version tag to `v1.0.2` to fix it. Thanks to @noah1510 !!
